pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'curl -O HelloWorld.java https://raw.githubusercontent.com/machayeswanth/Jenkins-Zero-To-Hero/main/multi-stage-multi-agent/helloworld.java'
        sh 'javac HelloWorld.java'
        sh 'java HelloWorld'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
